// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradeTracker.Persistence;

namespace TradeTracker.Persistence.Migrations
{
    [DbContext(typeof(TradeTrackerDbContext))]
    [Migration("20210301184412_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.1.21102.2");

            modelBuilder.Entity("TradeTracker.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Notional")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TradePrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = new Guid("e92878b0-adbf-4303-b677-b2f3361a3eac"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 5, 15, 19, 14, 0, 0, DateTimeKind.Utc),
                            Notional = 19.49m,
                            Quantity = 3.39m,
                            Symbol = "FI",
                            TradePrice = 5.75m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("56fdf7cf-d2dc-4b0e-a870-95a2f7e865ac"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 12, 13, 19, 21, 0, 0, DateTimeKind.Utc),
                            Notional = 395.37m,
                            Quantity = 4.92m,
                            Symbol = "QLQ",
                            TradePrice = 80.36m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("7654a3a9-a43d-4fa8-9043-8eb2b0e11626"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 3, 12, 14, 47, 0, 0, DateTimeKind.Utc),
                            Notional = 53.89m,
                            Quantity = 0.91m,
                            Symbol = "ABH",
                            TradePrice = 59.22m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("ec9b5224-7f96-408c-8bf1-88691c3aa49b"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 11, 20, 15, 1, 0, 0, DateTimeKind.Utc),
                            Notional = 21.82m,
                            Quantity = 1.61m,
                            Symbol = "XC",
                            TradePrice = 13.55m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("96a408a1-25e6-4ca1-84ab-42010937e151"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 6, 20, 15, 21, 0, 0, DateTimeKind.Utc),
                            Notional = 324.65m,
                            Quantity = 4.27m,
                            Symbol = "VFF",
                            TradePrice = 76.03m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("17877ec0-d6df-4dd9-b16e-db8567690af4"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 1, 18, 19, 50, 0, 0, DateTimeKind.Utc),
                            Notional = 63.37m,
                            Quantity = 1.17m,
                            Symbol = "RO",
                            TradePrice = 54.16m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("c98db727-02b6-4e9c-b7e3-fa603a5fe3f3"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 9, 17, 19, 32, 0, 0, DateTimeKind.Utc),
                            Notional = 307.84m,
                            Quantity = 3.66m,
                            Symbol = "DDP",
                            TradePrice = 84.11m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("08bf313f-d652-4d6e-9cc9-18ee3e442ecb"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 1, 3, 16, 35, 0, 0, DateTimeKind.Utc),
                            Notional = 114.22m,
                            Quantity = 1.26m,
                            Symbol = "A",
                            TradePrice = 90.65m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("f8d00f59-a7d4-4089-a0e2-ff8baafad582"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 8, 14, 14, 31, 0, 0, DateTimeKind.Utc),
                            Notional = 41.36m,
                            Quantity = 0.49m,
                            Symbol = "VDR",
                            TradePrice = 84.4m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("7a6cc702-6f5e-4e7c-b295-7fef5e4af9c8"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 8, 29, 20, 47, 0, 0, DateTimeKind.Utc),
                            Notional = 10.44m,
                            Quantity = 0.47m,
                            Symbol = "MG",
                            TradePrice = 22.22m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("c088a046-4e89-40fc-9d7d-d6ade047e784"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 10, 11, 16, 46, 0, 0, DateTimeKind.Utc),
                            Notional = 81.12m,
                            Quantity = 2.19m,
                            Symbol = "ASF",
                            TradePrice = 37.04m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("ecf4498b-2bbe-4c11-bc70-da66156d1f6f"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 10, 20, 17, 58, 0, 0, DateTimeKind.Utc),
                            Notional = 267.60m,
                            Quantity = 3.34m,
                            Symbol = "P",
                            TradePrice = 80.12m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("6760435a-7317-48a0-aae0-be22b8f4f1ff"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 3, 25, 16, 43, 0, 0, DateTimeKind.Utc),
                            Notional = 4.43m,
                            Quantity = 0.48m,
                            Symbol = "H",
                            TradePrice = 9.22m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("d57f85c4-a920-41c0-8f14-fe03dffcd19c"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 1, 4, 16, 18, 0, 0, DateTimeKind.Utc),
                            Notional = 67.50m,
                            Quantity = 1.33m,
                            Symbol = "B",
                            TradePrice = 50.75m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("ee8c7a5e-739e-4ca3-8fbb-81ef625d7cdf"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 1, 10, 17, 13, 0, 0, DateTimeKind.Utc),
                            Notional = 47.87m,
                            Quantity = 0.93m,
                            Symbol = "D",
                            TradePrice = 51.47m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("89486c95-d336-4005-8208-b4e88ab612a7"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 9, 28, 17, 36, 0, 0, DateTimeKind.Utc),
                            Notional = 86.40m,
                            Quantity = 4.17m,
                            Symbol = "OMS",
                            TradePrice = 20.72m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("2db6a7a9-9e3d-470e-a3a6-64cecf3afea5"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 7, 9, 20, 53, 0, 0, DateTimeKind.Utc),
                            Notional = 301.74m,
                            Quantity = 3.39m,
                            Symbol = "R",
                            TradePrice = 89.01m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("fa5529fd-b239-44e4-9c00-61b13a5c930e"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 11, 20, 16, 5, 0, 0, DateTimeKind.Utc),
                            Notional = 55.32m,
                            Quantity = 0.82m,
                            Symbol = "GS",
                            TradePrice = 67.46m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("0c87af59-f19e-489b-8c16-8403912ae53d"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 8, 24, 20, 5, 0, 0, DateTimeKind.Utc),
                            Notional = 219.80m,
                            Quantity = 2.44m,
                            Symbol = "G",
                            TradePrice = 90.08m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("64ddb121-395a-4488-8e3a-faf0d3b17626"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 4, 11, 16, 22, 0, 0, DateTimeKind.Utc),
                            Notional = 133.99m,
                            Quantity = 1.84m,
                            Symbol = "EW",
                            TradePrice = 72.82m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("cc03d612-c22e-49d8-8245-cb075b8239e2"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 7, 17, 17, 23, 0, 0, DateTimeKind.Utc),
                            Notional = 69.41m,
                            Quantity = 3.76m,
                            Symbol = "CW",
                            TradePrice = 18.46m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("c25c1d9d-ece8-4a49-bf5f-c13bf47b972b"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 8, 15, 20, 13, 0, 0, DateTimeKind.Utc),
                            Notional = 118.62m,
                            Quantity = 1.89m,
                            Symbol = "GLN",
                            TradePrice = 62.76m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("c00a2f96-c1f6-4526-9be6-6dbe00112325"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 9, 11, 18, 7, 0, 0, DateTimeKind.Utc),
                            Notional = 395.25m,
                            Quantity = 4.40m,
                            Symbol = "Y",
                            TradePrice = 89.83m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("e589af30-a383-46ba-baa9-236b339241d0"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 12, 8, 14, 40, 0, 0, DateTimeKind.Utc),
                            Notional = 55.35m,
                            Quantity = 4.89m,
                            Symbol = "E",
                            TradePrice = 11.32m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("24241bfb-c371-481e-9686-e8f666dfa5ab"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 5, 4, 14, 57, 0, 0, DateTimeKind.Utc),
                            Notional = 133.33m,
                            Quantity = 3.53m,
                            Symbol = "AZ",
                            TradePrice = 37.77m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("1051f73e-325d-4f5f-8c01-3a3edd90d10c"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 11, 27, 15, 13, 0, 0, DateTimeKind.Utc),
                            Notional = 26.57m,
                            Quantity = 4.10m,
                            Symbol = "A",
                            TradePrice = 6.48m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("7e91e86c-bdce-4ded-93d5-c988e2f0e324"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 2, 13, 19, 21, 0, 0, DateTimeKind.Utc),
                            Notional = 95.25m,
                            Quantity = 4.85m,
                            Symbol = "SSN",
                            TradePrice = 19.64m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("17eb4e11-dac0-48c3-aaf1-0f5842482efa"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 1, 14, 16, 6, 0, 0, DateTimeKind.Utc),
                            Notional = 74.49m,
                            Quantity = 2.70m,
                            Symbol = "NAA",
                            TradePrice = 27.59m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("880c6fb2-2093-4f0d-9953-f86776a6eda6"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 3, 20, 18, 5, 0, 0, DateTimeKind.Utc),
                            Notional = 25.35m,
                            Quantity = 3.57m,
                            Symbol = "P",
                            TradePrice = 7.1m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("ae361a0a-566a-46f7-b3fa-f52ebae15455"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 4, 1, 19, 36, 0, 0, DateTimeKind.Utc),
                            Notional = 59.31m,
                            Quantity = 0.71m,
                            Symbol = "EHZ",
                            TradePrice = 83.53m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("a31c36aa-6177-498e-bbd7-ab13e464f5eb"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 10, 18, 15, 48, 0, 0, DateTimeKind.Utc),
                            Notional = 290.16m,
                            Quantity = 3.86m,
                            Symbol = "OWJ",
                            TradePrice = 75.17m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("195d8258-631b-4304-b236-ca7ff793094f"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 11, 26, 16, 4, 0, 0, DateTimeKind.Utc),
                            Notional = 28.66m,
                            Quantity = 0.84m,
                            Symbol = "MLJ",
                            TradePrice = 34.12m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("9ebcd822-ef1d-4249-bc6e-043de5a625e1"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 12, 14, 18, 49, 0, 0, DateTimeKind.Utc),
                            Notional = 29.05m,
                            Quantity = 0.71m,
                            Symbol = "H",
                            TradePrice = 40.91m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("f5c3ad2c-cd29-4d6f-a011-4c2e7f068e05"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 7, 17, 20, 49, 0, 0, DateTimeKind.Utc),
                            Notional = 4.54m,
                            Quantity = 1.70m,
                            Symbol = "CEW",
                            TradePrice = 2.67m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("49484964-a865-48da-bb72-b31972d9e419"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 5, 14, 15, 32, 0, 0, DateTimeKind.Utc),
                            Notional = 229.67m,
                            Quantity = 2.69m,
                            Symbol = "QFU",
                            TradePrice = 85.38m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("ebeb3b4c-b4c9-43e8-8f67-8e5c0c498528"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 9, 20, 14, 55, 0, 0, DateTimeKind.Utc),
                            Notional = 245.50m,
                            Quantity = 4.87m,
                            Symbol = "VQ",
                            TradePrice = 50.41m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("d8da1274-f2e5-48bb-ac8f-b47f868f1c71"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2021, 1, 18, 18, 18, 0, 0, DateTimeKind.Utc),
                            Notional = 61.43m,
                            Quantity = 1.27m,
                            Symbol = "N",
                            TradePrice = 48.37m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("715e072f-4a9c-4442-955d-1660583480e3"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 11, 5, 19, 32, 0, 0, DateTimeKind.Utc),
                            Notional = 235.55m,
                            Quantity = 3.19m,
                            Symbol = "T",
                            TradePrice = 73.84m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("3db5f7c5-83f4-4769-a0cc-68d2d3dfeed2"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 7, 4, 14, 34, 0, 0, DateTimeKind.Utc),
                            Notional = 248.43m,
                            Quantity = 2.58m,
                            Symbol = "P",
                            TradePrice = 96.29m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("3d8d7e49-e8af-4288-9ea6-6291d56c753e"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 3, 8, 15, 30, 0, 0, DateTimeKind.Utc),
                            Notional = 10.91m,
                            Quantity = 0.73m,
                            Symbol = "JWB",
                            TradePrice = 14.94m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("301b54e5-6a9c-4580-99d3-9c759cd5804c"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 2, 20, 20, 17, 0, 0, DateTimeKind.Utc),
                            Notional = 79.72m,
                            Quantity = 1.00m,
                            Symbol = "LD",
                            TradePrice = 79.72m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("f5c28cfd-087e-421d-a237-95f14d1b06a6"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 3, 28, 16, 26, 0, 0, DateTimeKind.Utc),
                            Notional = 0.78m,
                            Quantity = 0.33m,
                            Symbol = "H",
                            TradePrice = 2.35m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("2b1f9660-f166-4317-a605-9110ef602c3c"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 8, 5, 17, 14, 0, 0, DateTimeKind.Utc),
                            Notional = 5.08m,
                            Quantity = 0.23m,
                            Symbol = "UA",
                            TradePrice = 22.08m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("176d11da-f8b2-432d-85f1-404876a81bc4"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 5, 22, 20, 54, 0, 0, DateTimeKind.Utc),
                            Notional = 355.39m,
                            Quantity = 4.05m,
                            Symbol = "EB",
                            TradePrice = 87.75m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("415130d8-28fd-4587-be23-71d81fa0884b"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 9, 3, 19, 59, 0, 0, DateTimeKind.Utc),
                            Notional = 63.32m,
                            Quantity = 1.56m,
                            Symbol = "IAC",
                            TradePrice = 40.59m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("f822912a-3e83-4413-a847-22424fdcdf6d"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 2, 7, 17, 44, 0, 0, DateTimeKind.Utc),
                            Notional = 156.89m,
                            Quantity = 4.76m,
                            Symbol = "B",
                            TradePrice = 32.96m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("3bac21d2-ba3e-4e44-8699-5f1a7af7838c"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 1, 9, 16, 34, 0, 0, DateTimeKind.Utc),
                            Notional = 12.61m,
                            Quantity = 0.56m,
                            Symbol = "KWW",
                            TradePrice = 22.52m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("b5b25433-3689-45a9-a2c2-ef667ce60848"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 7, 23, 19, 45, 0, 0, DateTimeKind.Utc),
                            Notional = 58.48m,
                            Quantity = 1.44m,
                            Symbol = "FF",
                            TradePrice = 40.61m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("6da224c4-e9ac-436c-974c-580342139d9e"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 9, 3, 20, 25, 0, 0, DateTimeKind.Utc),
                            Notional = 88.30m,
                            Quantity = 1.76m,
                            Symbol = "MTA",
                            TradePrice = 50.17m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("a9290284-9169-4a31-850e-de872a7a4305"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2021, 1, 6, 15, 15, 0, 0, DateTimeKind.Utc),
                            Notional = 120.45m,
                            Quantity = 1.60m,
                            Symbol = "ARR",
                            TradePrice = 75.28m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("6f88a89e-c518-4f73-a977-41a2614fc20b"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 7, 4, 17, 10, 0, 0, DateTimeKind.Utc),
                            Notional = 267.97m,
                            Quantity = 2.96m,
                            Symbol = "ZUC",
                            TradePrice = 90.53m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("b65e8403-d7c1-4bdd-b87e-04fd23da25da"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 8, 11, 15, 5, 0, 0, DateTimeKind.Utc),
                            Notional = 33.46m,
                            Quantity = 0.59m,
                            Symbol = "DS",
                            TradePrice = 56.72m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("7af05d95-fa2f-4a42-bfe5-1b375932bac1"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 2, 15, 19, 34, 0, 0, DateTimeKind.Utc),
                            Notional = 65.00m,
                            Quantity = 1.21m,
                            Symbol = "PSG",
                            TradePrice = 53.72m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("75d291aa-d7bb-41bf-86ec-2a06a6e02308"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 5, 31, 15, 29, 0, 0, DateTimeKind.Utc),
                            Notional = 16.77m,
                            Quantity = 0.35m,
                            Symbol = "X",
                            TradePrice = 47.91m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("2acada75-5655-4423-9710-533935000cfb"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 10, 5, 20, 9, 0, 0, DateTimeKind.Utc),
                            Notional = 250.92m,
                            Quantity = 2.87m,
                            Symbol = "G",
                            TradePrice = 87.43m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("7f0c96a3-cffc-4029-9a03-3dd9c5a5f2b0"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 1, 15, 17, 7, 0, 0, DateTimeKind.Utc),
                            Notional = 175.58m,
                            Quantity = 3.15m,
                            Symbol = "VKE",
                            TradePrice = 55.74m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("55afd82f-3c6a-46ba-8ea4-65027ee2e32d"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 1, 3, 20, 25, 0, 0, DateTimeKind.Utc),
                            Notional = 4.60m,
                            Quantity = 0.08m,
                            Symbol = "MEP",
                            TradePrice = 57.55m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("96048b52-18a8-415b-9171-b71eae490c2d"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 6, 24, 19, 23, 0, 0, DateTimeKind.Utc),
                            Notional = 15.92m,
                            Quantity = 2.30m,
                            Symbol = "XH",
                            TradePrice = 6.92m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("4869997e-0786-4738-817b-38be2c615283"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 2, 28, 20, 5, 0, 0, DateTimeKind.Utc),
                            Notional = 444.70m,
                            Quantity = 4.85m,
                            Symbol = "XGT",
                            TradePrice = 91.69m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("953f8987-36ba-4e74-942b-026a987751c7"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 12, 23, 17, 7, 0, 0, DateTimeKind.Utc),
                            Notional = 48.96m,
                            Quantity = 2.83m,
                            Symbol = "YRP",
                            TradePrice = 17.3m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("773d4896-1520-4033-bab9-06997d1602be"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 1, 14, 19, 31, 0, 0, DateTimeKind.Utc),
                            Notional = 36.27m,
                            Quantity = 0.46m,
                            Symbol = "PVN",
                            TradePrice = 78.85m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("2d0737de-96eb-4c51-b018-e8cfc65f5583"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 4, 19, 15, 13, 0, 0, DateTimeKind.Utc),
                            Notional = 241.69m,
                            Quantity = 3.48m,
                            Symbol = "UZH",
                            TradePrice = 69.45m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("246a7c24-f190-4de0-a423-863ee483ba48"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2021, 2, 17, 15, 51, 0, 0, DateTimeKind.Utc),
                            Notional = 28.97m,
                            Quantity = 1.65m,
                            Symbol = "Q",
                            TradePrice = 17.56m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("8f3946fb-ed1c-4cec-a440-874e64c90898"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 9, 3, 14, 53, 0, 0, DateTimeKind.Utc),
                            Notional = 74.73m,
                            Quantity = 1.09m,
                            Symbol = "QDK",
                            TradePrice = 68.56m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("7d683b85-e814-4991-b59b-e7f72290acd8"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 6, 3, 14, 47, 0, 0, DateTimeKind.Utc),
                            Notional = 69.54m,
                            Quantity = 2.55m,
                            Symbol = "BM",
                            TradePrice = 27.27m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("e6686070-a736-4f98-8a34-00e09fd8bb1e"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 1, 1, 19, 10, 0, 0, DateTimeKind.Utc),
                            Notional = 204.50m,
                            Quantity = 4.61m,
                            Symbol = "PX",
                            TradePrice = 44.36m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("a1074f78-9c25-4e8e-840d-f5c53ce27109"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 10, 15, 17, 25, 0, 0, DateTimeKind.Utc),
                            Notional = 2.51m,
                            Quantity = 0.76m,
                            Symbol = "AJO",
                            TradePrice = 3.3m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("7b903e4a-eb28-4a5c-bc7f-e459340ec8ee"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 6, 11, 20, 53, 0, 0, DateTimeKind.Utc),
                            Notional = 108.74m,
                            Quantity = 3.25m,
                            Symbol = "BH",
                            TradePrice = 33.46m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("d3a6302c-41b3-4d47-b9c1-7df115032666"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 12, 6, 18, 57, 0, 0, DateTimeKind.Utc),
                            Notional = 286.60m,
                            Quantity = 3.83m,
                            Symbol = "I",
                            TradePrice = 74.83m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("ccdabc42-a22c-4ac7-9356-90b19d2a3c7c"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 5, 23, 17, 58, 0, 0, DateTimeKind.Utc),
                            Notional = 20.93m,
                            Quantity = 3.46m,
                            Symbol = "EM",
                            TradePrice = 6.05m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("8f74da44-336b-4abb-ac5c-ee76bd083dac"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 7, 11, 17, 3, 0, 0, DateTimeKind.Utc),
                            Notional = 0.89m,
                            Quantity = 0.20m,
                            Symbol = "T",
                            TradePrice = 4.43m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("01948e07-2726-42fb-b2ac-c1c7c5e530ce"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 8, 1, 18, 1, 0, 0, DateTimeKind.Utc),
                            Notional = 45.50m,
                            Quantity = 2.98m,
                            Symbol = "DT",
                            TradePrice = 15.27m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("ece62ddb-5454-4ea1-a243-e85690e35029"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 5, 24, 18, 22, 0, 0, DateTimeKind.Utc),
                            Notional = 288.56m,
                            Quantity = 3.82m,
                            Symbol = "G",
                            TradePrice = 75.54m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("6051588e-1a77-420c-8fe4-e14800c4dd46"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 1, 12, 18, 32, 0, 0, DateTimeKind.Utc),
                            Notional = 214.09m,
                            Quantity = 2.82m,
                            Symbol = "FXV",
                            TradePrice = 75.92m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("282cccbd-60ca-4b59-8981-4db0d51a1035"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 8, 15, 19, 11, 0, 0, DateTimeKind.Utc),
                            Notional = 26.50m,
                            Quantity = 1.55m,
                            Symbol = "B",
                            TradePrice = 17.1m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("4d22aca6-48c0-4b09-b8e2-f72feddb2121"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 10, 30, 15, 42, 0, 0, DateTimeKind.Utc),
                            Notional = 434.72m,
                            Quantity = 4.89m,
                            Symbol = "RV",
                            TradePrice = 88.9m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("f97e61e3-196f-4d2e-9743-3523f55f97c0"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 12, 23, 15, 34, 0, 0, DateTimeKind.Utc),
                            Notional = 338.62m,
                            Quantity = 3.61m,
                            Symbol = "FR",
                            TradePrice = 93.8m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("aed77636-240b-45d6-a055-7eb0d5267d97"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 3, 21, 17, 43, 0, 0, DateTimeKind.Utc),
                            Notional = 58.72m,
                            Quantity = 2.83m,
                            Symbol = "P",
                            TradePrice = 20.75m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("fa9881ec-e528-4698-b979-69da43186268"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 6, 25, 15, 0, 0, 0, DateTimeKind.Utc),
                            Notional = 42.38m,
                            Quantity = 1.49m,
                            Symbol = "APC",
                            TradePrice = 28.44m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("1979e3b8-fb59-4e01-bd5c-87ff0b748612"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 1, 13, 14, 41, 0, 0, DateTimeKind.Utc),
                            Notional = 114.63m,
                            Quantity = 1.65m,
                            Symbol = "DI",
                            TradePrice = 69.47m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("c0d0f32d-35da-4e0a-b4ec-0f63306c8e87"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 11, 13, 20, 17, 0, 0, DateTimeKind.Utc),
                            Notional = 62.23m,
                            Quantity = 1.72m,
                            Symbol = "EJN",
                            TradePrice = 36.18m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("d4e542f3-d270-4951-86d0-4b747089239f"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 2, 10, 16, 6, 0, 0, DateTimeKind.Utc),
                            Notional = 276.24m,
                            Quantity = 4.48m,
                            Symbol = "MBQ",
                            TradePrice = 61.66m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("2c8bf62c-4cab-4230-83c6-8fea699c1735"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 1, 2, 16, 28, 0, 0, DateTimeKind.Utc),
                            Notional = 21.24m,
                            Quantity = 3.65m,
                            Symbol = "ZXH",
                            TradePrice = 5.82m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("5645697b-3ff8-4344-91fe-a05320aad70f"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 2, 27, 16, 9, 0, 0, DateTimeKind.Utc),
                            Notional = 221.00m,
                            Quantity = 3.56m,
                            Symbol = "I",
                            TradePrice = 62.08m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("6ae1f66c-ea8d-4aaa-a30f-81d2cd2ed314"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 5, 2, 14, 48, 0, 0, DateTimeKind.Utc),
                            Notional = 15.97m,
                            Quantity = 0.26m,
                            Symbol = "T",
                            TradePrice = 61.41m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("be32c350-e100-43a6-84ee-fc3efa749363"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 6, 11, 15, 40, 0, 0, DateTimeKind.Utc),
                            Notional = 9.71m,
                            Quantity = 0.14m,
                            Symbol = "YIS",
                            TradePrice = 69.33m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("8f9413e6-64af-4fa9-a264-05731a90a908"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 1, 16, 20, 20, 0, 0, DateTimeKind.Utc),
                            Notional = 377.64m,
                            Quantity = 3.83m,
                            Symbol = "WXL",
                            TradePrice = 98.6m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("e4eec332-eaf5-440d-aa07-f98f7286e352"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 8, 14, 20, 48, 0, 0, DateTimeKind.Utc),
                            Notional = 100.62m,
                            Quantity = 4.51m,
                            Symbol = "SFT",
                            TradePrice = 22.31m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("318e45b2-7b56-410d-9bdd-fc1a7d0a6f68"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 7, 3, 20, 41, 0, 0, DateTimeKind.Utc),
                            Notional = 36.97m,
                            Quantity = 1.30m,
                            Symbol = "D",
                            TradePrice = 28.44m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("4c21be1f-4584-4fea-83d0-1157b212063c"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 3, 6, 20, 8, 0, 0, DateTimeKind.Utc),
                            Notional = 82.11m,
                            Quantity = 1.21m,
                            Symbol = "LGJ",
                            TradePrice = 67.86m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("bf87f816-9b03-4398-944e-2e8dab4652f3"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 9, 21, 17, 10, 0, 0, DateTimeKind.Utc),
                            Notional = 123.05m,
                            Quantity = 4.92m,
                            Symbol = "TUZ",
                            TradePrice = 25.01m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("2318bf2e-78a9-4b60-928f-61cf5ddce4bd"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 7, 24, 18, 39, 0, 0, DateTimeKind.Utc),
                            Notional = 13.47m,
                            Quantity = 0.61m,
                            Symbol = "B",
                            TradePrice = 22.09m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("393687b5-c7ae-49a4-ac45-d4b74b9dd613"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 4, 23, 19, 43, 0, 0, DateTimeKind.Utc),
                            Notional = 181.84m,
                            Quantity = 3.05m,
                            Symbol = "TY",
                            TradePrice = 59.62m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("d619afd9-380b-4c9b-991d-9ca72e85382b"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 6, 25, 20, 57, 0, 0, DateTimeKind.Utc),
                            Notional = 37.55m,
                            Quantity = 0.73m,
                            Symbol = "YM",
                            TradePrice = 51.44m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("ece6a6dc-3592-4229-acc2-d29f31639a6e"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 8, 20, 15, 32, 0, 0, DateTimeKind.Utc),
                            Notional = 86.82m,
                            Quantity = 1.57m,
                            Symbol = "QCQ",
                            TradePrice = 55.3m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("3c762c14-640d-4df8-95e2-8e6ecb589413"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 7, 9, 18, 6, 0, 0, DateTimeKind.Utc),
                            Notional = 124.73m,
                            Quantity = 1.52m,
                            Symbol = "YH",
                            TradePrice = 82.06m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("c1a7a192-e635-424a-9e47-09e4e63e1e2c"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 5, 31, 18, 19, 0, 0, DateTimeKind.Utc),
                            Notional = 152.60m,
                            Quantity = 2.31m,
                            Symbol = "IR",
                            TradePrice = 66.06m,
                            TransactionType = 2
                        },
                        new
                        {
                            TransactionId = new Guid("9f10c57c-1f01-4650-b8eb-5f73ad866d4a"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2019, 11, 27, 20, 45, 0, 0, DateTimeKind.Utc),
                            Notional = 35.61m,
                            Quantity = 0.59m,
                            Symbol = "EQS",
                            TradePrice = 60.35m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("ec79e25b-4a6f-48bc-b35b-d6811f5f4408"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2020, 3, 30, 19, 34, 0, 0, DateTimeKind.Utc),
                            Notional = 44.94m,
                            Quantity = 1.72m,
                            Symbol = "NPR",
                            TradePrice = 26.13m,
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = new Guid("d1e78c05-f11c-4a65-888e-8bc16cf9f7b5"),
                            AccessKey = "00000000-0000-0000-0000-000000000000",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTime = new DateTime(2018, 11, 21, 19, 49, 0, 0, DateTimeKind.Utc),
                            Notional = 166.14m,
                            Quantity = 3.14m,
                            Symbol = "E",
                            TradePrice = 52.91m,
                            TransactionType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
